spring:
  datasource:
    url: jdbc:h2:mem:eshop
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring:
      jpa:
        hibernate:
          ddl-auto=create-drop:


